//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("http://sunnyone.org")]
[assembly: System.Reflection.AssemblyProduct("ScreenCaptureWrapper")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © sunnyone 2015-2015")]
[assembly: System.Reflection.AssemblyVersion("0.0.2.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.2.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.2.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCompany = "http://sunnyone.org";
    
    internal const string AssemblyProduct = "ScreenCaptureWrapper";
    
    internal const string AssemblyCopyright = "Copyright © sunnyone 2015-2015";
    
    internal const string AssemblyVersion = "0.0.2.0";
    
    internal const string AssemblyFileVersion = "0.0.2.0";
    
    internal const string AssemblyInformationalVersion = "0.0.2.0";
    
    private ThisAssembly() {
    }
}
